
export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';

export const CREAR_PLATOS = 'CREAR_PLATOS';
export const OBTENER_PLATOS = 'OBTENER_PLATOS';
export const EDITAR_PLATOS = 'EDITAR_PLATOS';
export const BORRAR_PLATOS = 'BORRAR_PLATOS';
export const OBTENER_PLATOID = 'OBTENER_PLATOID';

export const CREAR_COMENTARIOS = 'CREAR_COMENTARIOS';
export const OBTENER_COMENTARIOS = 'OBTENER_COMENTARIOS';
export const EDITAR_COMENTARIOS = 'EDITAR_COMENTARIOS';
export const BORRAR_COMENTARIOS = 'BORRAR_COMENTARIOS';

export const ELIMINAR_CARRITO = 'ELIMINAR_CARRITO'
export const AGREGAR_CARRITO = 'AGREGAR_CARRITO'
export const ACTULIZAR_CARRITO = 'ACTULIZAR_CARRITO'
export const VACIAR_CARRITO = 'VACIAR_CARRITO'

export const ELIMINAR_SERVICIO = 'ELIMINAR_SERVICIO'
export const AGREGAR_SERVICIO  = 'AGREGAR_SERVICIO'
export const ACTULIZAR_SERVICIO = 'ACTULIZAR_SERVICIO'
export const OBTENER_SERVICIO = 'OBTENER_SERVICIO'

export const ELIMINAR_CONTACTO = 'ELIMINAR_CONTACTO'
export const AGREGAR_CONTACTO  = 'AGREGAR_CONTACTO'
export const OBTENER_CONTACTO = 'OBTENER_CONTACTO'

export const ELIMINAR_RESERVA = 'ELIMINAR_RESERVA'
export const AGREGAR_RESERVA  = 'AGREGAR_RESERVA'
export const ACTULIZAR_RESERVA = 'ACTULIZAR_RESERVA'
export const OBTENER_RESERVA = 'OBTENER_RESERVA'
export const OBTENER_RESERVAID = 'OBTENER_RESERVAID'

export const ELIMINAR_RCOMPRA = 'ELIMINAR_RCOMPRA'
export const AGREGAR_RCOMPRA  = 'AGREGAR_RCOMPRA'
export const OBTENER_RCOMPRA = 'OBTENER_RCOMPRA'